const PERSONAL_FIELDS_MAP={
    NAME:'_n',
    PARENT_NAME:'pn',
    COMM_ADDRESS:'coa',
    PERMANENT_ADDRESS:"pa",
    DISTRICT:'d',
    STATE:'s',
    PINCODE:'p',
    CIVIC_STATUS:'cs',
    NATIVE_DISTRICT:'nd',
    DOB:'dob',
    GENDER:'g',
    NATIONALITY:'ny',
    NATIVITY:'nt',
    RELIGION:'r',
    COMMUNITY:'co',
    CASTE:'cas',
    AADHAR:'aa',
    SAME_AS_COMM_ADDRESS:'sac',
    MOTHER_TONGUE: 'mt'
};

const SPL_RESERVATION_MAP = {
    EMINENT_SPORTS_PERSON:'esp',
    EX_SERVICE_MAN:'ex',
    DIFF_ABLED_PERSON:'dap',
    DIFF_ABLED_TYPE:'adt',
    TFC_CENTER:'tfc'
};

const USER_FIELDS_KEY = {
    PERSONAL:'_p',
    SPL_RESERVATION:'_sr',
    SCHOLARSHIP: '_sp',
    SCHOOL:'_sc',
    PAYMENT:'_pa',
    STEPS:'_st',
    ACADEMIC:'_ac',
    APPLICATION_ID:'_aid'
};

const SCHOLARSHIP_FIELDS_MAP={
  PARENT_OCCUPATION:'po',
  ANNUAL_INCOME:'ai',
  FIRST_GRADUATE_TUITION_FEE_CONCESSION:'fgtfc',
  AVAILED_FIRST_GRADUATE_TUITION_FEE:'afgtf',
  AICTE_TUITION_FEE_WAIVER:'aitfw',
  POST_MATRIC_SCHOLARSHIP:'pms'
};

const SCHOOL_OF_STUDY_MAP = {
    STUDIED_IN_TAMILNADU:"sit",
    CLASS_VIII_YEAR_OF_PASSING:'cVIIIy',
    CLASS_VIII_SCHOOL_NAME:'cVIIIsn',
    CLASS_VIII_DISTRICT:'cVIIId',
    CLASS_VIII_STATE:'cVIIIs',
    CLASS_IX_YEAR_OF_PASSING:'cIXy',
    CLASS_IX_SCHOOL_NAME:'cIXsn',
    CLASS_IX_DISTRICT:'cIXd',
    CLASS_IX_STATE:'cIXs',
    CLASS_X_YEAR_OF_PASSING:'cXy',
    CLASS_X_SCHOOL_NAME:'cXsn',
    CLASS_X_DISTRICT:'cXd',
    CLASS_X_STATE:'cXs',
    CLASS_XI_YEAR_OF_PASSING:'cXIy',
    CLASS_XI_SCHOOL_NAME:'cXIsn',
    CLASS_XI_DISTRICT:'cXId',
    CLASS_XI_STATE:'cXIs',
    CLASS_XII_YEAR_OF_PASSING:'cXIIy',
    CLASS_XII_SCHOOL_NAME:'cXIIsn',
    CLASS_XII_DISTRICT:'cXIId',
    CLASS_XII_STATE:'cXIIs',
    CIVIC_STATUS_OF_SCHOOL:'csos',
    APPLY_CLASS_VIII_SCHOOL_ALL:'acVIIIsnta'
};

const ACADEMIC_INFO_FIELDS_MAP = {
  QUALIFYING_EXAM:'qe',
  NAME_OF_BOARD:'nbe',
  HSC_REGISTER_NO:'hrn',
  QUALIFIED_YEAR:'qy',
  HSC_GROUP:'hg',
  GROUP_CODE:'gc',
  MEDIUM_OF_INSTRUCTION:'mi',
  MATHS_MARKS_OBTAINED:'mmo',
  MATHS_MARKS_TOTAL:'mmt',
  MATHS_MONTH_PASSING:'mmp',
  MATHS_YEAR_PASSING:'myp',
  MATHS_REGISTER_NUMBER:'mrn',
  PHYSICS_MARKS_OBTAINED:'pmo',
  PHYSICS_MARKS_TOTAL:'pmt',
  PHYSICS_MONTH_PASSING:'pmp',
  PHYSICS_YEAR_PASSING:'pyp',
  PHYSICS_REGISTER_NUMBER:'prn',
  CHEMISTRY_MARKS_OBTAINED:'cmo',
  CHEMISTRY_MARKS_TOTAL:'cmt',
  CHEMISTRY_MONTH_PASSING:'cmp',
  CHEMISTRY_YEAR_PASSING:'cyp',
  CHEMISTRY_REGISTER_NUMBER:'crn',
  OPTIONAL_MARKS_OBTAINED:'omo',
  OPTIONAL_MARKS_TOTAL:'omt',
  OPTIONAL_MONTH_PASSING:'omp',
  OPTIONAL_YEAR_PASSING:'oyp',
  OPTIONAL_REGISTER_NUMBER:'orn',
  THEORY_MARKS_OBTAINED:'tmo',
  THEORY_MARKS_TOTAL:'tmt',
  THEORY_MONTH_PASSING:'tmp',
  THEORY_YEAR_PASSING:'typ',
  THEORY_REGISTER_NUMBER:'trn',
  PRACTICAL_I_MARKS_OBTAINED:'p1mo',
  PRACTICAL_I_MARKS_TOTAL:'p1mt',
  PRACTICAL_I_MONTH_PASSING:'p1mp',
  PRACTICAL_I_YEAR_PASSING:'p1yp',
  PRACTICAL_I_REGISTER_NUMBER:'p1rn',
  PRACTICAL_II_MARKS_OBTAINED:'p2mo',
  PRACTICAL_II_MARKS_TOTAL:'p2mt',
  PRACTICAL_II_MONTH_PASSING:'p2mp',
  PRACTICAL_II_YEAR_PASSING:'p2yp',
  PRACTICAL_II_REGISTER_NUMBER:'p2rn',
};

function getFieldPayload(fieldKey){
    switch (fieldKey) {
        case USER_FIELDS_KEY.PERSONAL:
            return PERSONAL_FIELDS_MAP;
        case USER_FIELDS_KEY.SPL_RESERVATION:
            return SPL_RESERVATION_MAP;
        case USER_FIELDS_KEY.SCHOLARSHIP:
            return SCHOLARSHIP_FIELDS_MAP;

        case USER_FIELDS_KEY.SCHOOL:
            return SCHOOL_OF_STUDY_MAP;
        case USER_FIELDS_KEY.ACADEMIC:
            return ACADEMIC_INFO_FIELDS_MAP;
        default:
            return {};

    }
}

module.exports = {
    PERSONAL_FIELDS_MAP,
    USER_FIELDS_KEY,
    SPL_RESERVATION_MAP,
    SCHOLARSHIP_FIELDS_MAP,
    SCHOOL_OF_STUDY_MAP,
    ACADEMIC_INFO_FIELDS_MAP,
    getFieldPayload,
};
